
logging:
  level:
    root: info
    com.example.mockitotest: debug
    org.springframework: debug
    org.springframework.boot.autoconfigure.logging: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/local-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
